name: Deploy to Docker Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PAT }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Check existing image
        id: check-image
        run: |
          EXISTS=$(docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }} > /dev/null 2>&1 && echo "true" || echo "false")
          echo "exists=${EXISTS}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        if: steps.check-image.outputs.exists == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_APP_HOST }}
          username: ${{ secrets.OCI_APP_USERNAME }}
          key: ${{ secrets.OCI_APP_KEY }}
          port: 22
          script: |
            if [ "$(sudo docker service ls -q -f name=invest-app-back 2>&1)" == "" ]; then sudo docker service create --name invest-app-back -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }} ; else sudo docker service update --image ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }} invest-app-back ; fi
