name: Deploy to Docker Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: sandropark/central-workflows/.github/workflows/docker-build-push.yml@b9b3f4548ecd9197d8d8f96ef7a163b4a9cd7241
    with:
      image_name: invest-app:${{ github.run_number }}
      dockerfile_path: Dockerfile
