name: Deploy to Docker Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_APP_HOST }}
          username: ${{ secrets.OCI_APP_USERNAME }}
          key: ${{ secrets.OCI_APP_KEY }}
          port: 22
          script: |
            if [ "$(docker service ls  -q -f name=invest-app-back 2>&1)" == "" ]; then docker service create --name invest-app-back -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }} ; else docker service update --image ${{ secrets.DOCKER_USERNAME }}/invest-app-back:${{ github.run_number }} invest-app-back ; fi
